### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Suzukiti-1029** [Suzukiti-1029/Protospace-34840#1]
# ProtoSpaceのURL(Heroku)

https://protospace-34840.herokuapp.com/

**よろしくお願いします**

**Comment by nishi418** [comment]
Suzukiti-1029さん
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
